name: Test Installing Qt

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        version: ['5.12.9']
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: "npm install"
        run: npm install

      - name: "npm run build"
        run: |
          npm run build-setup-python
          npm run build

      - name: Install Qt with options
        uses: ./
        with:
          modules: 'qtwebengine'
          version: ${{ matrix.version }}
          tools: 'tools_ifw,4.0.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'

      - name: Configure test project on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd tests/TestWithModules
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_DIR%/lib/cmake
          qmake
        shell: cmd
          
      - name: Configure test project on unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          cd tests/TestWithModules
          ls $Qt5_DIR/lib/cmake
          qmake
        shell: bash
